### ISSUE TITLE
Add addin to website to allow for automatic documentation

### ISSUE THREAD

**Issue by gep13** [xcomponent/Cake.XComponent#1]
This is just a suggestion, but think it would be a really good idea, to help with visibility of this addin.

i.e. get your addin listed here:

http://cakebuild.net/addins

Have a look at this PR:

cake-build/website#152

This assumes that you have added XML Documentation to your addin, as described here:

http://cakebuild.net/docs/contributing/documentation

Let me know if you have any questions. Thanks!

**Comment by Julien-Molina** [comment]
Hi,

Thanks a lot for this suggestion, we are currently working on the first version of this addin and it's not finished yet. We will provide the documentation as soon as possible.

Regards,
Julien

**Comment by gep13** [comment]
@Julien-Molina that is great news. Thanks for getting back to me.

**Comment by gep13** [comment]
@Julien-Molina just wanted to touch base on this again.  Is this addin now at a point for adding to the site?  Thanks!

**Comment by Julien-Molina** [comment]
@gep13 The current version of this adding is the first "usable" version so I think you can add it to the site. In the future I will add new methods in this adding should I tell you to update the site or is it automatic ?

**Comment by gep13** [comment]
@Julien-Molina once you have done the initial PR into the website, each time the website is built it will pull the latest version of the nuget package and include any new documentation.  The website is built reasonably frequently, but if you ship a new version, feel free to prod us and we can push out a new version.

**Comment by Julien-Molina** [comment]
@gep13 Here is the initial PR : https://github.com/cake-build/website/pull/317 :)

**Comment by gep13** [comment]
@Julien-Molina  Thank you!
