### ISSUE TITLE
Recommended changes resulting from automated audit

### ISSUE THREAD

**Issue by Jericho** [xcomponent/Cake.XComponent#17]
We performed an automated audit of your Cake addin and found that it does not follow all the best practices.

We encourage you to make the following modifications:

- [x] You are currently referencing Cake.Core 0.23.0. Please upgrade to 0.28.0
- [x] The Cake.Core reference should be private. Specifically, your addin's `.csproj` should have a line similar to this: `<PackageReference Include="Cake.Core" Version="0.28.0" PrivateAssets="All" />`
- [ ] Your addin should target netstandard2.0. Please note that there is no need to multi-target, netstandard2.0 is sufficient.

Apologies if this is already being worked on, or if there are existing open issues, this issue was created based on what is currently published for this package on NuGet.org and in the project on github.

**Comment by Julien-Molina** [comment]
Hi @Jericho, just a quick question, setting PrivateAssets="All" hides the dependency to the nuget package "Cake.core" in our nuget package.

![image](https://user-images.githubusercontent.com/8566695/41099397-aba66bb2-6a5e-11e8-929f-9dd256a29a9a.png)

Is it something that is expected ?

**Comment by Jericho** [comment]
yes it's expected and desired. Packages that are marked as "Private" are available in Visual Studio but are excluded from the nuget package that you generate. 

The reason why it's desirable to exclude the Cake DLLS (both Cake.Core and Cake.Common) from nuget packages is because Cake provides it's own version of Cake.Core and Cake.Common DLLs at the time when your addin is loaded in memory.
