### ISSUE TITLE
Add cake-contrib user to NuGet Package

### ISSUE THREAD

**Issue by gep13** [xcomponent/Cake.XComponent#4]
As you might be aware, I have been going through a process of asking maintainers of Cake Addins to add the cake-contrib user as a co-owner of the packages that are pushed to NuGet.org.  I have been able to get almost all maintainers to buy into this idea, and the result if the following:

https://www.nuget.org/profiles/cake-contrib

i.e. almost a complete list of all addins.  This means that in addition to the addin's list that we maintain of cakebuild.net, we also have this list, that people can use to find other addins.

Would you be interested in also adding the cake-contrib user as a co-owner of your package on NuGet.org?

Please let me know if you have any questions.

**Comment by Julien-Molina** [comment]
We added cake-contrib user as a co-owner, please let us know if it works as you expected.

**Comment by gep13** [comment]
@Julien-Molina that is great, thank you very much!
